### PR TITLE
Added crafting recipes for blocks

### PR DESCRIPTION
**Pull request by PseudonymPatel**

### CODE REVIEW

**Comment by canitzp** [comment]
Why have you moved the distil_test.json? This should be in it's old directory. It is a recipe for within the distillery itself.
Also why have you made a RecipeHandler? Recipes are completely json only, also the recipes for within the machines

**Comment by PseudonymPatel** [comment]
My bad for moving distil_test.
I made the RecipeHandler because of a couple of the recipes needed to be removed if the certain config flag is set, and to house any additional logic that goes with the crafting recipes (like the lantern color I saw mentioned, but that could possibly be in the lantern class), and also for that one furnace line, where there is no json for smelting. I will just condense all of it into one function and we can always remove later if there is no need for it.

**Comment by canitzp** [comment]
We should remove the RecipeHandler completely. Configs for removing recipes aren't wanted anymore. Moving it all to .json means that everyone can remove or manipulate them at their will. The lantern colors should be done through .json too, but didn't think about their implementation as of now

**Comment by PseudonymPatel** [comment]
I'm all for that, but where do you suppose I should put furnace/smelting recipes, since it's only 1 I can just stick in the Traincraft.java temporarily?

**Comment by canitzp** [comment]
Can't we register them through .json too? If not then yeah, we put it temporarily into the main class

**Comment by PseudonymPatel** [comment]
>To define a recipe for the furnace, you have to use GameRegistry.addSmelting(input, output, exp); as the smelting recipes are currently not JSON based.  

https://mcforge.readthedocs.io/en/1.12.x/utilities/recipes/

sadly, we can't use json unless we want to create our own json parser, which is simply not worth it
In newer versions of minecraft, however, everything is json

**Comment by canitzp** [comment]
Okay then we leave it in the temporary state. Are you done for this pr? Looks good for me

**Comment by PseudonymPatel** [comment]
I'm all done

**Comment by canitzp** [comment]
Oh one thing. The recipe json files should be all lower case. Otherwise they would comply the standards. So assembyTable1 is assembly_table_1

**Comment by PseudonymPatel** [comment]
That fixes it

**Pull request merged**
