### PR TITLE
Improved Contributing and discord links in Readme

### PR DESCRIPTION
**Pull request by PseudonymPatel**
Small change to README to hopefully make things easier to get started. (Will contribute code in the near future)

### CODE REVIEW

**Comment by canitzp** [comment]
After my commit today, you don't have to put Cyclops core into the mods folder.

**Comment by canitzp** [comment]
Can you also correct the resource issue? The correct solution would be to go into the gradle settings, set both drop downs to IntelliJ. Go to File->Project Structure and set the compiler output path to the build directory. At the end Restart with invalid cache.

**Comment by PseudonymPatel** [comment]
I can't get your instructions to fix the resource issue, I've tried a couple different things and I can't get the traincraft assets to go anywhere other than build/resources/main/assets. From my understanding, the IntelliJ options in the Gradle settings dropdowns is supposed to fix this, but it does not work for me.

**Comment by canitzp** [comment]
So I tested it now by cloning the repo again and after I applied all the settings I wrote above, it launched, crashed, I launched again and after that everything it fine and the resources are loaded

**Comment by PseudonymPatel** [comment]
Absolutely murdered git but I've added your instructions. I still am having a hard time on my end, but I trust that your instructions will fix it for others

**Comment by canitzp** [comment]
Okay thank you 😃. Hope you contribute more. Also whats you discord name?

**Comment by PseudonymPatel** [comment]
I'm the idiot who couldn't figure out how to do `genIntelliJRuns` lol (ComputerButter#8790) I've been looking at the TCItems stuff recently, will probably work on that area trying to get the easy things implemented

**Pull request merged**
